import os
os.system("python combine_cross_feature/all_combine_main.py")#对多个特征进行交叉合并
os.system("python extract_vector_length.py")#长度特征和长度转换率
os.system("python one_hot_statis_feature_5_fold.py")
os.system("python three_multi_statis_feature_5_fold_1_1_1.py")
os.system("python three_multi_statis_feature_5_fold_1_1_2.py")
os.system("python three_multi_statis_feature_5_fold_1_1_3.py")
os.system("python three_multi_statis_feature_5_fold_1_1_4.py")
os.system("python three_multi_statis_feature_5_fold_1_1_5.py")
os.system("python three_multi_statis_feature_5_fold_1_2.py")
os.system("python three_multi_statis_feature_5_fold_2_1.py")
os.system("python three_multi_statis_feature_5_fold_2_2.py")
os.system("python two_multi_statis_feature_5_fold_1.py")
os.system("python two_multi_statis_feature_5_fold_2.py")
os.system("python two_multi_statis_feature_5_fold_3.py")
os.system("python two_single_statis_feature_5_fold_1.py")
os.system("python two_single_statis_feature_5_fold_2.py")
os.system("python two_single_statis_feature_5_fold_3_1.py")
os.system("python two_single_statis_feature_5_fold_3_2.py")
os.system("python two_single_statis_feature_5_fold_3_3.py")
os.system("python user_statis_feature_5_fold.py")#用户转换率特征
os.system("python vector_statis_feature_5_fold.py")